# Site settings
title: Interface
email: gpinterface@gmail.com
description: "Grupo Interdisciplinar de Pesquisa em Filosofia e Cultura IFB/CNPq."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Marcos Ramon
  location: Onde
  social: Mais
  credits: Info

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/mrtollens
  - title: facebook
    url:
  - title: google-plus
    url: https://plus.google.com/+marcosramon

# Postal address (add as many lines as necessary)
address:
  - line: SGAN 610, Asa Norte / Campus Brasília - IFB 
  - line: Brasília, DF
  
# Credits content
credits: 'Interface é um grupo de pesquisa sobre Filosofia e Cultura, vinculado ao Instituto Federal de Brasília - IFB. Para mais informações mande um <a href="mailto:gpinterface@gmail.com">email</a>. Acesse também a <a href="http://dgp.cnpq.br/dgp/espelhogrupo/6419069911099653">página do grupo no diretório de grupos do CNPq</a>.'

# Build settings
markdown: kramdown
permalink: pretty
